### ISSUE TITLE
Support setting width/height

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/terminal-image#1]
Should be easy to support this through an options object, but I didn't want to do it before anyone had a need for it. PR welcome if so.

**Comment by RobertJGabriel** [comment]
Hey, currently working on this. Should have a pr in the evening sometime.

**Comment by piranna** [comment]
https://github.com/sindresorhus/terminal-image/blob/a659386d84576c645c69fb43e3517d4030223d66/index.js#L41-L42

`term-img` allow to define the sizes using chars as unit, so it could be used for both it and `jimp`. For the `preserveAspectRatio` option maybe would be checked to use the `resize()` method or any other similar one...

**Comment by goloroden** [comment]
I'm also interested in this, so I'm really looking forward to your PR, @RobertJGabriel 😊 

And BTW: As always, this is awesome work, @sindresorhus! Thanks a lot for all of your great open source work 😊

**Comment by goloroden** [comment]
PS: I have created a PR to address this issue, see #6

**Comment by piranna** [comment]
> And BTW: As always, this is awesome work, @sindresorhus! Thanks a lot for all of your great open source work

Yeah, I have started my project just some days ago, and I'm finding all your repos everywhere! Kudos! :-D

**Comment by yuanfux** [comment]
@sindresorhus  I'm building a terminal app and urgently need this feature.

**Comment by goloroden** [comment]
I didn’t want to wait any more, too, and built my own solution: https://www.npmjs.com/package/terminal-img

**Comment by yuanfux** [comment]
@goloroden nice, but I need something that doesn't directly output to the console. Guess I have to write my own too.

**Comment by goloroden** [comment]
If you give me a few hours, I can include that.

**Comment by goloroden** [comment]
@yuanfux I have just released a new version, `1.1.0`, which now includes a `draw.asString` function: https://www.npmjs.com/package/terminal-img

I think that it would be helpful to continue discussion about the `terminal-img` module in its own repository: https://github.com/thenativeweb/terminal-img

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/terminal-image/commit/c8caaa3bbe0477feda10b2d4c7cc20a2041fb072
