### ISSUE TITLE
Fails to install with npm install

### ISSUE THREAD

**Issue by vivianyoung** [sindresorhus/terminal-image#16]
When trying to install this package with npm, it stops at 
`$ npm install --save terminal-image
⸨ ░░░░░░░░░░░░░░░░░⸩ ⠦ fetchMetadata: sill resolveWithNewModule statuses@1.5.0 checking installable status` and does not proceed.

**Comment by sindresorhus** [comment]
This looks like a npm problem. You can report npm issues and get support here: https://npm.community But first, try upgrading to latest Node.js and npm version.
