### ISSUE TITLE
Send custom header when loading over HTTP

### ISSUE THREAD

**Issue by snobu** [sindresorhus/terminal-image#19]
When loading an image over HTTP, is there a way to send a custom header (like `Authorization: Bearer eyJXXXXX...`)?

**Comment by sindresorhus** [comment]
I will assume you're referring to https://github.com/sindresorhus/terminal-image#display-a-remote-image This is covered by the Got docs: https://github.com/sindresorhus/got

**Comment by snobu** [comment]
Ah yes you're right, makes sense, thanks!

**Comment by snobu** [comment]
One more, i can use any library that can fetch an image and return it as a Buffer, can't i?
