### ISSUE TITLE
Support animated GIFs

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/terminal-image#2]
https://github.com/oliver-moran/jimp/issues/166

or maybe with https://github.com/LinusU/cwasm-nsgif/issues/1

**Comment by Richienb** [comment]
@sindresorhus I built a library that exposes the same API that you requested in LinusU/cwasm-nsgif#1:

```js
const fs = require("fs");
const decodeGif = require("decode-gif");

decodeGif(fs.readFileSync("unicorn.gif"));
/*
{
  width: 220,
  height: 165,
  frames: [
    { timeCode: 0, data: [Uint8ClampedArray] },
	{ timeCode: 10, data: [Uint8ClampedArray] },
	...
  ]
}
*/
```

**Comment by RobertoMachorro** [comment]
So, would terminal-image just dump out to text a single frame you specify?

Or a series of all the frames one after the other?

**Comment by Richienb** [comment]
@RobertoMachorro The frames are rendered and outputted to a function. I'm thinking of an API like this:

```js
const terminalImage = require("terminal-image")
const logUpdate = require("log-update")

terminalImage.gif('unicorn.gif', {width: '50%', height: '50%'}, logUpdate)
```

**Comment by sindresorhus** [comment]
Sounds good. I think it should just default to using `logUpdate` and we can add an optional option (not parameter) to use a different renderer.

**Comment by Richienb** [comment]
@sindresorhus What function names should be used when using a buffer or a file?
