### ISSUE TITLE
Legacy versions of mkdirp are no longer supported.

### ISSUE THREAD

**Issue by zedd3v** [sindresorhus/terminal-image#20]
Cannot install I'm getting an error by npm-

npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note
that the API surface has changed to use Promises in 1.x.)
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/notmasteryet/jpgjs.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:

**Comment by Richienb** [comment]
terminal-image > @sindresorhus/jimp > mkdirp

**Comment by sindresorhus** [comment]
I think we can switch the the original `jimp` version now.

**Comment by Richienb** [comment]
the the?
