### ISSUE TITLE
Switching from Chalk to Colorette to reduce file size.

### ISSUE THREAD

**Issue by equinusocio** [sindresorhus/terminal-image#30]
Are you interested to switch from Chalk to Colorette to reduce the bundle size?

https://bundlephobia.com/result?p=chalk@4.1.0
<img width="536" alt="Screenshot 2020-07-23 at 12 33 25" src="https://user-images.githubusercontent.com/10454741/88277267-b59e1c00-cce0-11ea-8d27-5c0046f937b0.png">

https://bundlephobia.com/result?p=colorette@1.2.1
<img width="522" alt="Screenshot 2020-07-23 at 12 33 09" src="https://user-images.githubusercontent.com/10454741/88277247-acad4a80-cce0-11ea-91fb-193bcab75223.png">

**Comment by sindresorhus** [comment]
No. And your argument makes no sense. This is Node.js, not the browser. A few kilobytes difference doesn't matter. Especially not when Chalk is considerably better.

**Comment by equinusocio** [comment]
What a stupid response. I have not mentioned performance but bundle size/filesize. So for you is more important to use your products/packages rather than care about what people are downloading, right?

PostCSS is not (using your words) "browser" too, but they care about dependencies and the weight of the whole package because they know that PostCSS is used inside many other bigger applications and execution times and the package weight matter. This is Node, [of course](https://deerwaves.com/wp-content/uploads/2014/10/meme-nicolas-cage-you-dont-say-wide.jpg). But you said all.
