### ISSUE TITLE
Render raw pixel data from ArrayBuffer source

### ISSUE THREAD

**Issue by jozanza** [sindresorhus/terminal-image#4]
How hard would it be to support rendering raw `ArrayBuffer` pixel data like how `CanvasRenderingContext2D` works in browsers? I'd also love to help with this support if I can get pointed in the right direction! :)

**Comment by piranna** [comment]
Seems #5 would fix that, too.

**Comment by sindresorhus** [comment]
@piranna How would #5 fix that?

**Comment by piranna** [comment]
> You’d definitely have to at least pass a width along with the raw pixel data somehow. ImageData is basically a native js data structure that encapsulates this.

Jimp [already support](https://github.com/oliver-moran/jimp/blob/a9fb1f1e87c1eea54612366d9aee8da481df2696/index.js#L182-L183) ArrayBuffer as input...

**Comment by jozanza** [comment]
So I looked at the index.js file a little closer, and here’s my proposal @sindresorhus 

### terminalImage.imageData(imageData)

Returns a `Promise<string>` with the ansi escape codes to display the image.

#### imageData

Type: `ImageData | { height: number, width: number, data: Uint8ClampedArray }`

[ImageData](https://developer.mozilla.org/en-US/docs/Web/API/ImageData) (or ImageData-like object) representing raw pixel colors and image dimensions.

—-

The rationale here is that I have some browser HTMLCanvas-related code that works on top of ArrayBuffers that I’d like to port to the node environment and print on the cli. To transform it into an image format like jpg or png would be bad since this data structure is already 100% prepared to be converted to ANSI pixels.

I’d be happy to create a PR for this as well, if you think it’s a welcome addition to this lib.

**Comment by sindresorhus** [comment]
@jozanza Sounds good to me.

@piranna Thoughts?

---

> ImageData (or ImageData-like object) representing raw pixel colors and image dimensions.

There no concept of `ImageData` in Node.js, so it would only accept an ImageData-like object.

**Comment by piranna** [comment]
> @piranna Thoughts?

Since Jimp accept ArrayBuffer, I would take a look first about the exact format that it needs, and if `term-img` accept it too. If there's some difference between them or the format (maybe Jimp accept an ArrayBuffer with the file content instead of the raw data, for example), then it's ok to me to add the extra function, or maybe better piggy-back the current one adding a new input type.
