### ISSUE TITLE
CommonJS support

### ISSUE THREAD

**Issue by lmmfranco** [sindresorhus/terminal-image#40]
The lib doesn't work with node out of the box. To require with commonjs we have to do some wizardry like this:
```js
(async () => {
    const terminalImage = (await import("terminal-image")).default;
    console.log(await terminalImage.file('pikachu.png'));
})();
```

While requiring a commonjs lib on a ESM file is quite simple:
```js
import someCommonJsLib from "some-commonjs-lib";
```

Consider reverting back to common js.

Anyway, thanks for the wonderfull library.

**Comment by sindresorhus** [comment]
I don't plan to move back to CommonJS. I recommend staying on the previous version if ESM is a problem for you.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
