### ISSUE TITLE
Remove conversion to buffer

### ISSUE THREAD

**Issue by piranna** [sindresorhus/terminal-image#5]
https://github.com/sindresorhus/terminal-image/blob/a659386d84576c645c69fb43e3517d4030223d66/index.js#L47

Both `term-img` and `jimp` accept as first parameter both a buffer of a filepath, so usage of `readFIle()` is superfluous and also add some limits...

**Comment by sindresorhus** [comment]
It was an intentional choice as I plan to switch out Jimp with something custom.

> so usage of readFIle() is superfluous and also add some limits...

What limitations?

**Comment by piranna** [comment]
> It was an intentional choice as I plan to switch out Jimp with something custom.

Oh, well... I was using it more extensively in the changes I'm doing to #6... :-/


> What limitations?

File vs Buffer and access to libraries internal features.

**Comment by sindresorhus** [comment]
> Oh, well... I was using it more extensively in the changes I'm doing to #6... :-/

Feel free to take advantage of Jimp right now. I don't plan on switching right now. Just a long-term goal, as Jimp is needlessly heavy for what this module needs. I just prefer to keep the file reading separate.

> File vs Buffer and access to libraries internal features.

This doesn't clarify what limitations reading the file ourselves causes. It should make no difference, other than 10 characters of needless code.
