### ISSUE TITLE
Move fallback to own module?

### ISSUE THREAD

**Issue by piranna** [sindresorhus/terminal-image#9]
I find the fallback to have enough entity to work standalone. What about moving it to it's own module and use it as dependency of this one? It would also allow to make it without behaviour constrains to be the same as `term-img`, doing that constrains in this module instead...

**Comment by sindresorhus** [comment]
> I find the fallback to have enough entity to work standalone. What about moving it to it's own module and use it as dependency of this one?

This is actually the main module. The iTerm stuff is just for niceness on iTerm terminals. I'm not sure it makes sense to introduce yet another module for this.

> It would also allow to make it without behaviour constrains to be the same as term-img, doing that constrains in this module instead...

What constraints? If the iTerm thing makes it hard to achieve something here, I'm happy to move the iTerm support to a sub-method.
